swagger: '2.0'
info:
  title:  Gifting cash the cashless way. 

  contact:
    name: "Cloud9"
    url: "https://developer.cloud9.com"
    email: "TB.channels.API.platform@nl.abnamro.com"
  license:
    name: "Copyright (c) All Rights Reserved."
    url: "https://developer.cloud9.com"
  version: "1.0"
  x-apiType: open
  description: |-
    
    # Overview
    
    ## Introduction
    
    With Gifty you can easily create digital cash to give to who you want the way you want, without the need of going to the ATM ever again! It allows the gifter and the receiver of digital cash to create, pay, gift and redeem in a simple, smart and convenient way.
    
     Gifty allows you to gift money, without needing any information of the recipient. You easily can create a link for the recipient which they can use to redeem the money directly into their bank account.
     
    ## Gaining Access
    
    Users need to register with ABN AMRO developer portal to access this api. Please refer to the _Gaining Access_ part of the [link](https://developer.abnamro.com/api/tikkie-v1/tikkie-api-documentation).
  
    ## Authentication
    Please refer to the _Authentication_ part of the [link](https://developer.abnamro.com/api/tikkie-v1/tikkie-api-documentation)

    ---
    
    # Functional Overview
    
    A simple user journey of using the API resources. 
    
    * The person gifting (gifter) the digital cash creates the cash by means of _/cashGiftCreation_, and recieves a link representing the gift. The gifter can share this link (via mail, sms, QrCode) to the recipient of the gift.<br>
    * The recipient can view the details of the digital cash using _/cashGiftDetails_ and can redeem the digital cash by adding their bank account and name in a request towards _/cashGiftRedemption_.<br>
    
    <br>
    <br>
    
    ![Swagger logo](https://raw.githubusercontent.com/vivikul/gifty/master/Gifty.png)

    ---
    
host: "api.cloud9.com"
basePath: /gifty/v1
tags: 
- name: "Gifty"
  description: | 
    Provides REST resources that can be consumed for the creation, retrieval and redemption of digital cash. <br>

schemes:
- "https"
paths:
  /cashGiftCreation:
    post:
      tags:
        - "cashGiftCreation"
      summary:  This resource creates a new cash gift that is redeemable. 
      description: | 
        A post request to this resource creates digital cash, in response to which a unique Id (that can be converted to a link) is received. This unique Id can be shared with the recipient. _Consider this as an envelope with cash._ <br> 
        The gifter can share the link to the recipient in the way he prefers.
        
        _idealTxnId:_
        This is a unique valid ideal Txn Id that needs to be provided for the cashGift to be created successfully.
        
        _redemptionCode:_
        Along with the unique Id, is received a 6 digit redemptionCode on gifters emailId or  phoneNumber.
        So it is important to provide either of it while creating the request. 
      operationId: createCashGift
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
        - name: cashGiftCreationInstruction
          in: body
          required: true
          schema:
            $ref: '#/definitions/CashGiftCreationInstruction'

      responses:
        '201':
          description: successful operation
          schema:
            $ref: '#/definitions/CashGiftCreationResponse'
        '400':
          description: Bad request/parameter error
          schema:
            $ref: '#/definitions/Errors'
        '401':
          description: Unauthorised
        '403':
          description: Not Allowed/Forbidden
          schema:
            $ref: '#/definitions/Errors'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Errors'
      security: 
      - gifty-security:
        - "gifty:digital-cash"
  /cashGiftDetails/{giftId}:
    get:
      tags:
        - "viewCashGift"
      summary: This resource allows to retrieve details of the existing gift.
      description: A get request to this resource with a valid giftId returns the details of the gift, like the amount and  the expiration date. 
      operationId: viewCashGiftDetails
      produces:
      - "application/json"
      parameters:
        - name: giftId
          in: path
          description: The unique Id of the gift 
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/CashGiftCreationResponse'
        '400':
          description: Bad request/parameter error
          schema:
            $ref: '#/definitions/Errors'
        '401':
          description: Unauthorised
        '403':
          description: Not Allowed/Forbidden
          schema:
            $ref: '#/definitions/Errors'
        '404':
          description: Resource not found
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Errors'
      security: 
      - gifty-security:
        - "gifty:digital-cash"
  /cashGiftRedemption:
    post:
      tags:
        - "cashGiftRedemption"
      summary: Redeem the digital cash.
      description: "A post request to this resource redeems the digital cash on behalf of the recipient. The request should contain the IBAN and the name of the recipient, to which the digital cash amount is credited after successful redemption. </br> </br>
      Redemption Code: To defy brute force attack the request must also be supplied with a redemption code, that the gifter has received with the link"
      operationId: redeemCashGift
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
        - name: redemptionInstruction
          in: body
          required: true
          schema:
            $ref: '#/definitions/CashGiftRedemption'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/CashGiftRedemptionResponse'
        '400':
          description: Bad request/parameter error
          schema:
            $ref: '#/definitions/Errors'
        '401':
          description: Unauthorised
        '403':
          description: Not Allowed/Forbidden
          schema:
            $ref: '#/definitions/Errors'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Errors'
      security: 
      - gifty-security:
        - "gifty:digital-cash"

definitions:
  CashGiftCreationInstruction:
    type: object
    description: Contains all the data required to successfully create the digital cash.
    required:
      - giftAmount
      - message
      - gifterDetails
      - idealTxnId
    properties:
      giftAmount:
        $ref: '#/definitions/CashGiftAmount'
      message:
        $ref: '#/definitions/CashGiftmessage'
      gifterDetails:
        $ref: '#/definitions/GifterDetails'
      recipientDetails:
        $ref: '#/definitions/RecipientDetails'
      idealTxnId:
        description: A valid iDeal transaction id. This is the transactionId shared by the iDeal service. 
        type: string
        pattern: ^[0-9A-Za-z]{16}$
        minLength: 3
        maxLength: 70
  CashGiftCreationResponse:
    type: object
    description: The response of successful 'createCashGift' operation  
    properties:
      giftDetails:
        $ref: '#/definitions/CashGiftDetails'
      gifterDetails:
        $ref: '#/definitions/GifterDetails'
      recipientDetails:
        $ref: '#/definitions/RecipientDetails'
      expirationDate:
        type: string
        description: The last date one can redeem the digital cash.
        format: date

  CashGiftRedemption:
    type: object
    description: This object encapsulates the information required for redeeming the digital cash.
    required:
      - giftId
      - recipientAccountNumber
      - recipientName
      - redemptionCode
    properties:
      giftId:
        $ref: '#/definitions/CashGiftId'
      recipientAccountNumber:
        type: string
        description: The NL IBAN account number of the recipient.
        pattern: '^NL[0-9]{2}[A-Z]4[0-9]{8}$'
        example: NL62ABNA0528362518
      recipientName:
        description: The name of the recipient.
        type: string
        minimum: 3
        maximum: 70
        example: Happy Person
      redemptionCode:
        description: A seceret redemption code that is required for successful redemption.
        type: string
        pattern: ^[0-9]6
        example: 537273
  CashGiftRedemptionResponse:
    type: object
    description: The Corporate Payment resource to create.
    required:
      - result
    properties:
      result:
        description: The amount of the transaction always positive.
        type: string
        enum: 
         - SUCCESS
         - FAILURE
      timestamp:
        type: string
        description: The IBAN account number of the recipient.
        pattern: '^[A-Z0-9]{10,22}$'
      reason:
        type: string
        description: The reason behind FAILURE
        enum: 
          - INVALID_CASH_GIFT_ID
          - ALREADY_REDEEMED
          - EXPIRED

  CashGiftDetails:
    type: object
    description: Holds the details of the digital cash
    required: 
    - giftAmount
    - status
    - id
    properties:
      giftAmount:
        $ref: '#/definitions/CashGiftAmount'
      message:
        $ref: '#/definitions/CashGiftmessage'
      status:
        $ref: '#/definitions/CashGiftStatus'
      id:
        $ref: '#/definitions/CashGiftId'
        
  GifterDetails:
    type: object
    description: Holds the details of the person who is gifting. Atleast one of emailId and phoneNumber should be present to make sure the gifter receiver gets the redemptionCode.
    required: 
      - name
    properties:
      name:
        $ref: '#/definitions/Name'
      emailId:
        $ref: '#/definitions/EmailId'
      phoneNumber: 
        $ref: '#/definitions/PhoneNumber'
      
  RecipientDetails:
    type: object
    description: Holds the details of the person who is the recipient of the digital cash
    properties:
      name:
        $ref: '#/definitions/Name'
      emailId:
        $ref: '#/definitions/EmailId'
      phoneNumber: 
        $ref: '#/definitions/PhoneNumber'

  Name:
    type: string
    description: The name of the person.
    minLength: 3
    maxLength: 70
    example: Foo Bar
  EmailId:
    description: The email id of the person.
    type: string
    pattern: ^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$
    example: john.doe@universal.com
  PhoneNumber: 
    description: The mobile phone number of a person. Only Dutch numbers.
    type: string
    pattern: ^06[0-9]{8}$
    example: 0685782295
  CashGiftAmount:
    description: The amount of the cash to be gifted.
    type: number
    format: double
    maximum: 750
    minimum: 0.5
    multipleOf: 0.5
    example: 50
  CashGiftmessage:
    type: string
    description: A message to the recipient of the digital cash.
    minLength: 3
    maxLength: 140
    example: Congratulations on your 50th Birthday
  CashGiftStatus:
    type: string
    description: The status of the digital cash.
    enum:
      - CREATED
      - READY2REDEEM
      - REDEEMED
      - EXPIRED
    example: READY2REDEEM
  CashGiftId:
    description: A unique id of the digital cash.
    type: string
    pattern: ^[0-9A-Za-z]{16}
    example: GXV3g95DGDFrffsf
  Errors:
    type: object
    description: an array of error messsages
    properties:
      errors:
        type: array
        items:
          $ref: '#/definitions/Error'
        maxItems: 10
        minItems: 1
  Error:
    type: object
    required:
      - code
      - status
    properties:
      code:
        type: string
        example: INVALID_AMOUNT
        description: >-
          The unique error code key which is used to lookup the message in the
          content management system.
      message:
        type: string
        example: Amount is not valid.
        description: Default message explaining the unsuccessful response
      traceId:
        type: string
        example: f1b554d8-406a-4301-b549-d539a5e885ae
        description: The unique id for end to end tracing of the error.
      status:
        type: string
        example: 400
        description: HTTP status code
      params:
        type: array
        description: >-
          Optionally, a message in the content management system may contain
          dynamic parameters. This attributes gives the values of those dynamic
          parameters.
        items:
          type: string
          example: null
        maxItems: 10
        minItems: 0
securityDefinitions:
  gifty-security:
    type: "oauth2"
    description: "" 
    flow: implicit
    authorizationUrl: "https//api-sandbox.abnamro.com/v1/oauth/token"
    scopes: 
       gifty:digital-cash: "Create the digital cash."
